#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ANTDIV]
// [ANTDIV]$

// $[BTL_BUTTON]
#define HAL_BTL_BUTTON_ENABLE              (1)

#define BSP_BTL_BUTTON_PIN                 (2U)
#define BSP_BTL_BUTTON_PORT                (gpioPortD)

// [BTL_BUTTON]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE               (HAL_CLK_HFCLK_SOURCE_HFRCO)
#define HAL_CLK_PLL_CONFIGURATION          (HAL_CLK_PLL_CONFIGURATION_NONE)
#define BSP_CLK_LFXO_PRESENT               (1)
#define HAL_CLK_EM4CLK_SOURCE              (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define HAL_CLK_EM23CLK_SOURCE             (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define BSP_CLK_HFXO_PRESENT               (1)
#define BSP_CLK_LFXO_INIT                   CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_CTUNE                 (79U)
#define HAL_CLK_RTCCCLK_SOURCE             (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define HAL_CLK_WDOGCLK_SOURCE             (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define BSP_CLK_LFXO_FREQ                  (32768U)
#define BSP_CLK_HFXO_FREQ                  (38400000UL)
#define BSP_CLK_HFXO_CTUNE                 (133)
#define BSP_CLK_HFXO_INIT                   CMU_HFXOINIT_DEFAULT
// [CMU]$

// $[COEX]
// [COEX]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[EZRADIOPRO]
// [EZRADIOPRO]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IADC0]
// [IADC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
// [LED]$

// $[LETIMER0]
// [LETIMER0]$

// $[LFXO]
// [LFXO]$

// $[MODEM]
// [MODEM]$

// $[PA]
// [PA]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[PTI]
// [PTI]$

// $[SERIAL]
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
#define BSP_SPINCP_NWAKE_PIN               (3U)
#define BSP_SPINCP_NWAKE_PORT              (gpioPortD)

#define BSP_SPINCP_NHOSTINT_PIN            (2U)
#define BSP_SPINCP_NHOSTINT_PORT           (gpioPortD)

#define BSP_SPINCP_USART_PORT              (HAL_SPI_PORT_USART2)
#define BSP_SPINCP_CS_PIN                  (3U)
#define BSP_SPINCP_CS_PORT                 (gpioPortC)

#define BSP_SPINCP_CLK_PIN                 (2U)
#define BSP_SPINCP_CLK_PORT                (gpioPortC)

#define BSP_SPINCP_MISO_PIN                (1U)
#define BSP_SPINCP_MISO_PORT               (gpioPortC)

#define BSP_SPINCP_MOSI_PIN                (0U)
#define BSP_SPINCP_MOSI_PORT               (gpioPortC)

#define HAL_SPINCP_FREQUENCY               (6400000UL)
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[TIMER2]
// [TIMER2]$

// $[TIMER3]
// [TIMER3]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
// [USART0]$

// $[USART1]
// [USART1]$

// $[USART2]
#define PORTIO_USART2_CLK_PIN              (2U)
#define PORTIO_USART2_CLK_PORT             (gpioPortC)

#define PORTIO_USART2_CS_PIN               (3U)
#define PORTIO_USART2_CS_PORT              (gpioPortC)

#define PORTIO_USART2_RX_PIN               (1U)
#define PORTIO_USART2_RX_PORT              (gpioPortC)

#define PORTIO_USART2_TX_PIN               (0U)
#define PORTIO_USART2_TX_PORT              (gpioPortC)

#define HAL_USART2_ENABLE                  (1)

#define BSP_USART2_CS_PIN                  (3U)
#define BSP_USART2_CS_PORT                 (gpioPortC)

#define BSP_USART2_CLK_PIN                 (2U)
#define BSP_USART2_CLK_PORT                (gpioPortC)

#define BSP_USART2_MISO_PIN                (1U)
#define BSP_USART2_MISO_PORT               (gpioPortC)

#define BSP_USART2_MOSI_PIN                (0U)
#define BSP_USART2_MOSI_PORT               (gpioPortC)

#define HAL_USART2_FREQUENCY               (6400000UL)
// [USART2]$

// $[VCOM]
// [VCOM]$

// $[VUART]
// [VUART]$

// $[WDOG]
// [WDOG]$

#if defined(_SILICON_LABS_MODULE)
#include "sl_module.h"
#endif


#endif /* HAL_CONFIG_H */

